# Generated by Django 2.2.1 on 2020-04-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vlan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlans',
            old_name='VlanName',
            new_name='vlanName',
        ),
    ]
