# Generated by Django 2.2.1 on 2020-04-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_interfaces_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='devicelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
